#!/bin/bash
# Default configuration

SORT_BUFFER_SIZE=256K
THREAD_STACK=256K

SLOW_QUERY_TIME=10
MAX_CONNECTIONS=96

INNODB_BUFFER_POOL_SIZE=256M
INNODB_LOG_BUFFER_SIZE=16M
INNODB_BUFFER_POOL_INSTANCES=2
INNODB_MEMORY_POOL_DICT=16M
INNODB_DATA_FILES=ibdata1:512M:autoextend
INNODB_AUTOEXTEND_SIZE=128

MYISAM_KEY_BUFFER_SIZE=4M
MYISAM_READ_BUFFER_SIZE=1M

BINLOG_ENABLE=0
BINLOG_BASENAME=$HOSTNAME
BINLOG_EXPIRE_DAYS=0
BINLOG_CACHE_SIZE=512K
BINLOG_SYNC=0
